pipeline {
    environment {
    registry = "rmuruge/maven-project"
    application = "maven-project"
    registryCredential = 'dockerhub'
        dockerImage = ''
    }
    
    agent any
    
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        
        stage('Build image') {
            steps{
                script {
                    dockerImage = docker.build registry + ":$BUILD_NUMBER"
                }
            }
        }

        
        stage('Push Image') {
            steps{
                script {
                    docker.withRegistry( '', registryCredential ) {
                        dockerImage.push()
                    }
                }
            }
        }
        stage('Deploy Image') {
            steps{
                sh "set +e; docker rm $application; set -e"
                sh "docker run -it --name $application $registry:$BUILD_NUMBER /bin/bash" 
                }
        
        }  
    }
}
